// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY-SmRNJjqKS8CCJRKTVzE7XV1k3hrDS4',
    appId: '1:890831068257:web:632589d8d568a49d555e20',
    messagingSenderId: '890831068257',
    projectId: 'task-37647',
    authDomain: 'task-37647.firebaseapp.com',
    storageBucket: 'task-37647.firebasestorage.app',
    measurementId: 'G-MJNPFR3CMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt_DgbTSE9roe9Tx0-7VydgMrTQhPW2qk',
    appId: '1:890831068257:android:7a2f269cfcac14e5555e20',
    messagingSenderId: '890831068257',
    projectId: 'task-37647',
    storageBucket: 'task-37647.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4_ELl4LX2Tg4JMApQah98FmbG-aLf83M',
    appId: '1:890831068257:ios:1a334858f129e1bc555e20',
    messagingSenderId: '890831068257',
    projectId: 'task-37647',
    storageBucket: 'task-37647.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4_ELl4LX2Tg4JMApQah98FmbG-aLf83M',
    appId: '1:890831068257:ios:1a334858f129e1bc555e20',
    messagingSenderId: '890831068257',
    projectId: 'task-37647',
    storageBucket: 'task-37647.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY-SmRNJjqKS8CCJRKTVzE7XV1k3hrDS4',
    appId: '1:890831068257:web:3b054b5b45c70af6555e20',
    messagingSenderId: '890831068257',
    projectId: 'task-37647',
    authDomain: 'task-37647.firebaseapp.com',
    storageBucket: 'task-37647.firebasestorage.app',
    measurementId: 'G-F8D7XGQK21',
  );
}
